name: Analysis

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest
    # continue-on-error: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  
    - name: Test with pylint
      id: pylint
      run: |
        pip install pylint
        pylint hw2_debugging.py --exit-zero >> pylint.txt
        cat pylint.txt
  type-check:
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Install Pyright
      run: npm install -g pyright
    
    - name: Test with pyright
      id: pyright
      run: |
          pyright hw2_debugging.py > pyright.txt
          ls
          cat pyright.txt
      continue-on-error: true
        
