name: Analysis

on: [push, pull_request]

jobs:
  analyse:

    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  
    - name: Test with pylint
      id: pylint
      run: |
        pip install pylint
        pylint hw2_debugging.py --exit-zero >> pylint.txt
        cat pylint.txt
    - name: Test with pyright
      id: pyright
      run: |
          pip install pyright
          pyright --outputjson hw2_debugging.py >> pyright.json
          exit 0
          cat pyright.json
        
