name: Autopep8

on: [push, pull_request]

permissions:
  contents: write

jobs:
  pep8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin ${{ github.ref_name }} --rebase || true  # Ensure the workflow continues even if there are no changes

    - name: Run autopep8 to format code
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py
        autopep8 --in-place --aggressive --aggressive rand.py

    - name: Stage changes
      run: |
        git add hw2_debugging.py rand.py

    - name: Commit formatted files
      run: |
        git commit -m "Autopep8: Format files"

    - name: Pull latest changes again
      run: |
        git pull origin ${{ github.ref_name }} --rebase || true

    - name: Push changes
      run: git push origin ${{ github.ref_name }}