name: Autopep8

on: [push, pull_request]

permissions:
  contents: write

jobs:
  pep8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # Install autopep8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    # Pull the latest changes before running autopep8 to avoid conflicts
    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin ${{ github.ref_name }} --rebase || true

    # Run autopep8 to format code
    - name: Run autopep8 to format code
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py
        autopep8 --in-place --aggressive --aggressive rand.py

    # Stage the modified files
    - name: Stage changes
      run: |
        git add hw2_debugging.py rand.py

    # Commit the changes
    - name: Commit formatted files
      run: |
        git commit -m "Autopep8: Format files" || echo "No changes to commit"

    # Pull again to ensure that the local branch is updated after the commit
    - name: Pull latest changes again
      run: |
        git pull origin ${{ github.ref_name }} --rebase || true

    # Push the changes to the repository
    - name: Push changes
      run: |
        git push origin ${{ github.ref_name }}
