name: Autopep8

on: [push, pull_request]

jobs:
  pep8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8 to format code
      run: |
        mkdir -p post_traces  # Ensure the directory exists
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py >> post_traces/autopep8_trace.txt
        autopep8 --in-place --aggressive --aggressive rand.py >> post_traces/autopep8_trace.txt
        cat post_traces/autopep8_trace.txt

    # Stage the modified files
    - name: Stage changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add hw2_debugging.py rand.py

    # Pull latest changes to avoid conflicts
    - name: Pull latest changes
      run: git pull origin ${{ github.ref_name }} --rebase

    # Commit the formatted files
    - name: Commit changes
      run: |
        git commit -m "Autopep8: Format"

    # Push the changes to the repository
    - name: Push changes
      run: git push origin ${{ github.ref_name }}

