name: Autopep8

on: [push, pull_request]

jobs:
  pep8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Run autopep8 to format code
      run: |
        mkdir -p post_traces  # Ensure the directory exists
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py >> post_traces/autopep8_trace.txt
        autopep8 --in-place --aggressive --aggressive rand.py >> post_traces/autopep8_trace.txt
        cat post_traces/autopep8_trace.txt

    - name: Upload autopep8 trace artifact
      uses: echapmanFromBunnings/upload-artifact@3.0.0
      with:
        name: autopep8_trace
        path: post_traces/autopep8_trace.txt
