name: Pylint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest
    # continue-on-error: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  
    - name: Test with pylint
      id: pylint
      run: |
        pip install pylint
        pylint hw2_debugging.py --exit-zero >> pylint.txt
        cat pylint.txt
    - name: Upload artifact
      uses: echapmanFromBunnings/upload-artifact@3.0.0
      with:
        name: pylint_trace
        path: pylint.txt
