name: Pylint

on: [push, pull_request]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # Install Pylint
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    # Pull the latest changes before running Pylint to avoid conflicts
    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin ${{ github.ref_name }} --rebase || true

    # Run Pylint and append traces to post_traces/pylint_trace.txt
    - name: Run Pylint and append traces
      run: |
        mkdir -p post_traces  
        pylint hw2_debugging.py rand.py > pylint.txt || true  
        if [ -f post_traces/pylint_trace.txt ]; then
          cat pylint.txt >> post_traces/pylint_trace.txt
        else
          mv pylint.txt post_traces/pylint_trace.txt
        fi

    # Stage and commit the Pylint trace file
    - name: Commit Pylint trace to repository
      if: always()
      run: |
        git add post_traces/pylint_trace.txt
        git commit -m "Append Pylint traces" || echo "No changes to commit"
        git pull origin ${{ github.ref_name }} --rebase || true  
        git push origin ${{ github.ref_name }} 
