name: Pylint

on: [push, pull_request]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  

    - name: Test with pylint
      id: pylint
      run: |
        pip install pylint
        pylint hw2_debugging.py >> post_traces/pylint.txt
        PYLINT_EXIT_CODE=$?
        cat post_traces/pylint.txt
        exit $PYLINT_EXIT_CODE

    - name: Commit pylint trace to repository
      if: always()  # Ensures that this step runs regardless of the previous step's result
      uses: EndBug/add-and-commit@v8
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Commit pylint traces'
        add: 'pylint.txt'
        path: 'post_traces/pylint_trace.txt'
        cwd: './'
