name: Pylint

on: [push, pull_request]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    # Run pylint and append traces to post_traces/pylint_trace.txt
    - name: Run pylint and append traces
      run: |
        mkdir -p post_traces
        pylint hw2_debugging.py > pylint.txt
        if test -f post_traces/pylint_trace.txt; then
          cat pylint.txt >> post_traces/pylint_trace.txt
        else
          mv pylint.txt post_traces/pylint_trace.txt
        fi

    # Commit the updated pylint trace file
    - name: Commit pylint trace to repository
      if: always()
      uses: EndBug/add-and-commit@v8
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Append pylint traces'
        add: 'post_traces/pylint_trace.txt'
