name: Pyright

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest
    # continue-on-error: true

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  
    
  type-check:
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Pyright
      run: npm install -g pyright
    
    - name: Test with pyright
      id: pyright
      run: |
          pyright --outputjson hw2_debugging.py >> pyright.json || echo "Pyright errors detected" >> pyright.json
          cat pyright.json
      # continue-on-error: true
    - name: Upload artifact
      uses: echapmanFromBunnings/upload-artifact@3.0.0
            
      with:
        name: pyright_trace
        path: pyright.json