name: Pyright

on: [push, pull_request]

permissions:
  contents: write

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # Install Pyright
    - name: Install Pyright
      run: npm install -g pyright

    # Pull the latest changes before running Pyright to avoid conflicts
    - name: Pull latest changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin ${{ github.ref_name }} --rebase || true

    # Run Pyright and append traces to post_traces/pyright_trace.txt
    - name: Run Pyright and append traces
      run: |
        mkdir -p post_traces  # Ensure the post_traces directory exists
        echo "Running Pyright on $(date)" >> post_traces/pyright_trace.txt  
        pyright --outputjson hw2_debugging.py rand.py >> post_traces/pyright_trace.txt || echo "Pyright errors detected" >> post_traces/pyright_trace.txt

    # Stage and commit the Pyright trace file
    - name: Commit Pyright trace to repository
      if: always()
      run: |
        git add post_traces/pyright_trace.txt
        git commit -m "Append Pyright traces" || echo "No changes to commit"
        git pull origin ${{ github.ref_name }} --rebase || true 
        git push origin ${{ github.ref_name }}  # Push changes to the repository
