
name: Testing

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build  
        pip install pylint
        pip install autopep8

    - name: Run autopep8 to format code
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py >> post_traces/autopep8_trace.txt
        autopep8 --in-place --aggressive --aggressive rand.py >> post_traces/autopep8_trace.txt
    
    - name: Run Pylint and save traces
      run: |
          pylint hw2_debugging.py >> post_traces/pylint_trace.txt
    
    - name: Test with pytest
      id: pytest
      run: |
        pip install pytest pytest-cov
        pytest hw2_test.py --doctest-modules --cov=hw2_debugging --cov-report=xml --cov-report=html
      continue-on-error: true   
    
    

    - name: List files after tests
      run: ls -R .

    - name: Upload coverage to Codecov (always run this step)
      if: always()
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml

    - name: Fail the job if tests failed
      if: ${{ steps.pytest.outcome == 'failure' }}  # This step will cause the job to fail if the pytest step failed
      run: exit 1
        